lbs:
  centos:
    '6':
      repos: ['http://obs.kolabsys.com/repositories/Kolab:/3.4/CentOS_6/Kolab:3.4.repo', 'http://obs.kolabsys.com/repositories/Kolab:/3.4:/Updates/CentOS_6/Kolab:3.4:Updates.repo', 'http://mirror.de.leaseweb.net/epel/6/x86_64/epel-release-6-8.noarch.rpm', 'http://obs.kolabsys.com/repositories/Kolab:/Development/CentOS_6/']
      keys: ['http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x830C2BCF446D5A45']
    '7':
      repos: ['http://obs.kolabsys.com/repositories/Kolab:/3.4/CentOS_7/', 'http://obs.kolabsys.com/repositories/Kolab:/3.4:/Updates/CentOS_7/', 'epel-release', 'http://obs.kolabsys.com/repositories/Kolab:/Development/CentOS_7/', 'http://download.opensuse.org/repositories/openSUSE:Tools/CentOS_7/openSUSE:Tools.repo']
      keys: ['http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x830C2BCF446D5A45']
  debian:
    wheezy:
      repos:
        Kolab34: 'deb http://obs.kolabsys.com/repositories/Kolab:/3.4/Debian_7.0/ /'
        Kolab34Updates: 'deb http://obs.kolabsys.com/repositories/Kolab:/3.4:/Updates/Debian_7.0/ /'
        KolabDevelopment: 'deb http://obs.kolabsys.com/repositories/Kolab:/Development/Debian_7.0/ /'
      keys: ['http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x830C2BCF446D5A45', 'http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x4796B710919684AC']
    jessie:
      repos:
        Kolab34: 'deb http://obs.kolabsys.com/repositories/Kolab:/3.4/Debian_8.0/ /'
        Kolab34Updates: 'deb http://obs.kolabsys.com/repositories/Kolab:/3.4:/Updates/Debian_8.0/ /'
        KolabDevelopment: 'deb http://obs.kolabsys.com/repositories/Kolab:/Development/Debian_8.0/ /'
      keys: ['http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x830C2BCF446D5A45', 'http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x4796B710919684AC']
