#!/bin/bash

reload_apache()
{
    if apache2ctl configtest 2>/dev/null; then
        invoke-rc.d apache2 $1 || true
    else
        echo "Your apache2 configuration is broken, so we're not restarting it for you."
    fi
}


case "$1" in
    remove)
        if [ -e "/etc/apache2/sites-enabled/iRony.conf" ]; then
            a2dissite iRony.conf
        fi
        reload_apache reload
    ;;
esac

