#!/bin/sh

set -e

reload_apache()
{
    if apache2ctl configtest 2>/dev/null; then
        invoke-rc.d apache2 $1 || true
    else
        echo "Your apache2 configuration is broken, so we're not restarting it for you."
    fi
}


case "$1" in
    upgrade|install)
        # old version had problems with the apache conf created as directoy instead of file
        if [ -e "/etc/apache2/sites-available/chwala/chwala.conf" ]; then
            DIR=$(mktemp -d)
            mv /etc/apache2/sites-available/chwala/* $DIR/
            rmdir /etc/apache2/sites-available/chwala/
            mv $DIR/chwala.conf /etc/apache2/sites-available/chwala
            rmdir $DIR
        fi

        # rename old apache/http sites rom sitename to sitename.conf
        if [ -e /etc/apache2/sites-available/chwala -a ! -e /etc/apache2/sites-available/chwala.conf ]; then
            if [ -h /etc/apache2/sites-enabled/chwala ]; then
                a2dissite chwala
            fi
            mv /etc/apache2/sites-available/chwala /etc/apache2/sites-available/chwala.conf
            a2ensite chwala.conf
            reload_apache
        fi
    ;;
esac

exit 0
