#!/bin/sh

set -e

#EXTRA#
#DEBHELPER#

fixperms() {
    chown -R www-data:adm \
        /var/lib/kolab-syncroton \
        /var/log/kolab-syncroton
    chmod 750 \
        /var/lib/kolab-syncroton \
        /var/log/kolab-syncroton
}

reload_apache()
{
    if apache2ctl configtest 2>/dev/null; then
        invoke-rc.d apache2 $1 || true
    else
        echo "Your apache2 configuration is broken, so we're not restarting it for you."
    fi
}

update_database() {
    /usr/share/roundcubemail/bin/updatedb.sh \
        --dir /usr/share/doc/kolab-syncroton/SQL \
        --package syncroton \
        >/dev/null 2>&1 || :
}


case "$1" in
    configure)
        fixperms
        update_database
        a2enmod rewrite >/dev/null 2>&1 || true
        if [ -e "/etc/apache2/sites-available/kolab-syncroton.conf" -a ! -e "/etc/apache2/sites-enabled/kolab-syncroton.conf" ]; then
            a2ensite kolab-syncroton.conf
        fi
        reload_apache reload
    ;;
esac

exit 0

