#!/bin/sh

set -e

reload_apache()
{
    if apache2ctl configtest 2>/dev/null; then
        invoke-rc.d apache2 $1 || true
    else
        echo "Your apache2 configuration is broken, so we're not restarting it for you."
    fi
}


case "$1" in
    upgrade|install)
        # rename old apache/http sites rom sitename to sitename.conf
        if [ -e /etc/apache2/sites-available/kolab-syncroton -a ! -e /etc/apache2/sites-available/kolab-syncroton.conf ]; then
            if [ -h /etc/apache2/sites-enabled/kolab-syncroton ]; then
                a2dissite kolab-syncroton
            fi
            mv /etc/apache2/sites-available/kolab-syncroton /etc/apache2/sites-available/kolab-syncroton.conf
            a2ensite kolab-syncroton.conf
            reload_apache
        fi
    ;;
esac

exit 0

