#!/bin/sh

set -e

#EXTRA#
#DEBHELPER#

fixperms() {
    chown -R www-data:adm \
        /var/cache/kolab-freebusy \
        /var/log/kolab-freebusy
    chmod 750 \
        /var/cache/kolab-freebusy \
        /var/log/kolab-freebusy
}

reload_apache()
{
    if apache2ctl configtest 2>/dev/null; then
        # Workaround for #2050
        # invoke-rc.d apache2 $1 || true
        /etc/init.d/apache2 stop && sleep 3 && /etc/init.d/apache2 start || true
    else
        echo "Your apache2 configuration is broken, so we're not restarting it for you."
    fi
}


case "$1" in
    configure)
        fixperms
        a2enmod rewrite >/dev/null 2>&1 || true
        if [ -e "/etc/apache2/sites-available/kolab-freebusy.conf" -a ! -e "/etc/apache2/sites-enabled/kolab-freebusy.conf" ]; then
            a2ensite kolab-freebusy.conf
        fi
        reload_apache reload
    ;;
esac

exit 0

