#!/bin/bash

reload_apache()
{
    if apache2ctl configtest 2>/dev/null; then
        # Workaround for #2050
        # invoke-rc.d apache2 $1 || true
        /etc/init.d/apache2 stop && sleep 3 && /etc/init.d/apache2 start || true
    else
        echo "Your apache2 configuration is broken, so we're not restarting it for you."
    fi
}


case "$1" in
    remove)
        if [ -e "/etc/apache2/sites-enabled/kolab-freebusy.conf" ]; then
            a2dissite kolab-freebusy.conf
        fi
        reload_apache reload
    ;;
esac

