Document: libcalendaring
Title: Debian libcalendaring Manual
Author: <insert document author here>
Abstract: This manual describes what libcalendaring is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libcalendaring/libcalendaring.sgml.gz

Format: postscript
Files: /usr/share/doc/libcalendaring/libcalendaring.ps.gz

Format: text
Files: /usr/share/doc/libcalendaring/libcalendaring.text.gz

Format: HTML
Index: /usr/share/doc/libcalendaring/html/index.html
Files: /usr/share/doc/libcalendaring/html/*.html
