#!/bin/sh

set -e

#EXTRA#
#DEBHELPER#

fixperms() {
    chown -R www-data:www-data \
        /var/cache/kolab-webadmin \
        /var/log/kolab-webadmin
    chmod 750 \
        /var/cache/kolab-webadmin \
        /var/log/kolab-webadmin
}

reload_apache()
{
    if apache2ctl configtest 2>/dev/null; then
        invoke-rc.d apache2 $1 || true
    else
        echo "Your apache2 configuration is broken, so we're not restarting it for you."
    fi
}


case "$1" in
    configure)
        fixperms
        a2enmod rewrite > /dev/null || true
        if [ -e "/etc/apache2/sites-available/kolab-webadmin.conf" -a ! -e "/etc/apache2/sites-enabled/kolab-webadmin.conf" ]; then
            a2ensite kolab-webadmin.conf
        fi
        reload_apache reload
    ;;
esac

exit 0
