#!/bin/sh

set -e

#EXTRA#
#DEBHELPER#

reload_apache()
{
    if apache2ctl configtest 2>/dev/null; then
        invoke-rc.d apache2 $1 || true
    else
        echo "Your apache2 configuration is broken, so we're not restarting it for you."
    fi
}


case "$1" in
    remove)
        a2dissite kolab-webadmin.conf > /dev/null || true
        reload_apache restart
    ;;
esac

exit 0
